spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digital?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 2354818484
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false